name: magnolia3-gpu
channels: !!python/tuple
- defaults
dependencies:
- conda-forge::altair
- conda-forge::pandas
- conda-forge::matplotlib
- python=3.5
- numpy
- scipy
- scikit-learn
- seaborn
- pip:
  - python_speech_features
  - theano
  - soundfile
