name: magnolia3-cpu
channels: !!python/tuple
- defaults
dependencies:
- conda-forge::altair
- conda-forge::pandas
- conda-forge::matplotlib
- flask
- h5py
- python=3.5
- numpy
- scipy
- scikit-learn
- seaborn
- pip:
  - python_speech_features
  - theano
  - soundfile
  - keras
