name: magnolia3
channels: !!python/tuple
- defaults
dependencies:
- conda-forge::altair
- conda-forge::pandas
- conda-forge::matplotlib
- python=3
- numpy
- scipy
- scikit-learn
- seaborn
- pip:
  - tensorflow
  - python_speech_features
  - theano
  - soundfile

